### PR TITLE
Create Language Folder & twentysixteen.pot file

### PR DESCRIPTION
**Pull request by mkrdip**
Pull request for https://github.com/WordPress/twentysixteen/issues/41

### CODE REVIEW

**Comment by grappler** [comment]
With the new translation system on WordPress.org there is no need to create a POT file. translate.wordpress.org automatically fetches all of the strings.

**Comment by ihorvorotnov** [comment]
@grappler it's not there yet and we need to test the theme in different languages. And we use GH forks for testing and development, not the .org version. I suppose we can have translations in this Github repo but prevent it from syncing to SVN repo.

**Comment by mkrdip** [comment]
@grappler, 

There is no locale for **en_US** at [WordPress Locales](https://translate.wordpress.org/). 

image

I think each theme needs an initial pot file. Correct me if I'm wrong. I'll glad to know. 

Thanks.

**Comment by grappler** [comment]
TwentySixteen is on GlotPress now and ready to be translated. https://translate.wordpress.org/locale/de/default/wp-themes/twentysixteen

As you can see the German translating is complete.

@mkrdip There is no need for the en_US. The theme's strings are all in en_US.

**Comment by dd32** [comment]
Yep, nothing needs doing here to support the language packs which WordPress.org offers.

Might be worth dropping the `/languages/` folder referenced in the `load_theme_textdomain()` call though, since it's no longer needed for hosted themes, and doesn't exist.

**Pull request closed without merging**
