### PR TITLE
apply browser-specific hyphens/word-breaks to titles #34

### PR DESCRIPTION
**Pull request by SeanChDavis**
#34

### CODE REVIEW

**Comment by SeanChDavis** [comment]
As requested. Checked all browsers and everything looks great. :+1:

**Comment by valendesigns** [comment]
Needs a refresh before merge.

**Comment by SeanChDavis** [comment]
@valendesigns Refreshed but I don't know what the fail is all about. :unamused:

**Comment by valendesigns** [comment]
Don't worry about them, they existed before your PR and are unrelated to your code.

**Pull request closed without merging**
