### PR TITLE
Superfluous printf

### PR DESCRIPTION
**Pull request by tfrommen**
This pull request removes a superfluous `printf()` call from a template file.

### CODE REVIEW

**Comment by iamtakashi** [comment]
Thanks for the PR. See #130 for the style of if statement.

**Comment by tfrommen** [comment]
@iamtakashi I don't understand. If you want to see curly braces here, then have a look at some lines below my edit. There is also the `if () : endif;` syntax in use. If something else, please enlighten me. ;)

**Comment by iamtakashi** [comment]
Oh, you're breaking out of PHP and into HTML inside the statement. `endif;` is correct. Sorry about that!

**Comment by tfrommen** [comment]
@iamtakashi no problem at all. :)

**Pull request merged**
