### PR TITLE
Clearly label non-accessible color schemes to comply with Theme Revie…

### PR DESCRIPTION
**Pull request by cgrymala**
Addresses #180

### CODE REVIEW

**Comment by karmatosed** [comment]
Whilst I apprecaite your advocacy for accessibility. Not all color schemes have to be accessible, we are doing so for the default and also several others. As a result we are not going to rename like this.

**Comment by cgrymala** [comment]
Does this mean that TwentySixteen will not pass the Theme Review process?

**Comment by karmatosed** [comment]
Not at all, it's not a requirement.

**Comment by cgrymala** [comment]
It is a requirement, as clearly stated here (emphasis mine):

> The default settings will be the only color scheme checked. If a theme offers multiple color schemes, only the default scheme is required to pass these guidelines. _Alternative themes should be clearly labeled if they do not meet accessibility guidelines._

**Comment by karmatosed** [comment]
This has already had an accessibility review from @davidakennedy, lets get his opinion as he is a member of the team and does those reviews too. I think you are taking the term label as literally labelling, but it perhaps more means indicate in docs. This is my interpretation.

**Comment by joedolson** [comment]
David and I chatted, and we think we'll drop that from the review guidelines; it's not really practical to test given our workflow and time. We're going to focus on making sure defaults meet standards. We have some doubts about the idea of labeling anything as specifically inaccessible, because it implies that the defaults _are_ accessible, which we can't really guarantee in any absolute sense.

**Comment by davidakennedy** [comment]
@cgrymala Thanks for the issue and pull request!

Like Joe said, we plan to drop that wording from the requirements. It's something that we've never required of any themes that had color schemes. And it's not a great idea anyway because we shouldn't be labeling items that aren't accessible, but instead focusing on what we can make accessible by default.

The other important thing to remember is that themes can't really _be_ accessible because it's up to the user/site owner to ensure that the content they place in WordPress and the theme is accessible. We can never guarantee that. We can only give users the best starting point possible. I think having the default color scheme accessible provides that.

**Comment by cgrymala** [comment]
I agree with the point that we should be focusing on what we can make accessible, rather than trying to simply label things that aren't.

That's why my initial support went behind making the color schemes in TwentySixteen meet contrast guidelines (issue #177), but that issue was closed before there was even any discussion on the matter; and @iamtakashi pointed to the Theme Review guidelines saying that only the default color scheme needed to have accessible contrast.

I feel like you guys are running around in circles to defend poor accessibility within this theme.

I, better than most, understand that a theme in itself does not make a site accessible, but one thing I can guarantee you: _If the color schemes that come with the theme aren't accessible in the first place, it doesn't matter what content the site owner puts in the site, it will never be accessible._

By avoiding the color contrast issues, you are avoiding giving the users the "best starting point possible", and, instead, giving them one default color scheme with decent contrast, one alternative color scheme with good contrast, two alternative color schemes with poor contrast, and one alternative color scheme with terrible contrast.

The WordPress community claims to be passionate about accessibility, and claims to put accessibility first, but when push comes to shove, I feel like there are a lot of excuses as to why it's not worth it to make things accessible, and that putting together 1 out of 5 color schemes that's truly accessible, contrast-wise, is considered the best anyone can do.

If anything, the default WordPress theme should be held to a higher standard than any other theme that goes through the theme review process, rather than bending and changing the rules of the theme review process to meet the low accessibility standards of the default theme.

**Comment by joedolson** [comment]
I think that it would be great if all of the available color schemes for Twenty Sixteen met color contrast guidelines; however, we're still going to remove the wording about labeling things as inaccessible from the review guidelines. I'm not personally invested in what happens with Twenty Sixteen; but from a theme review guidelines perspective, it's too burdensome to have to review every color scheme available and verify. Those of us who are doing these reviews simply don't have the time to address those.

But let's also be clear that not doing something that's in the best interest of the users just because "it's not required in the guidelines" is a kind of lame reason not to do it. Great - it's not required. Whatever. That's not the important question for a major project like this - the question should be whether we feel that it's worthwhile to do it and something we can reasonably achieve. 

FYI - this change in the theme review guidelines has been on my to-do list since the community summit last October; it just got done now because the topic came up.

**Pull request closed without merging**
