### PR TITLE
added blue color scheme

### PR DESCRIPTION
**Pull request by junrillg**
Added a Blue color scheme as some people prefer to see some blue color on their site.

### CODE REVIEW

**Comment by SeanChDavis** [comment]
This blue palette seems a little off to me. It looks more green in my opinion.

2015-08-29 at 9 37 pm

There's a blue palette included in the with Twenty Fifteen that also uses the same simple "Blue" setting name. The difference between the two is pretty strong. 

2015-08-29 at 9 40 pm

I'd at least advise against giving the color schemes the same titles as they look nothing alike in regards to hue.

**Comment by junrillg** [comment]
I see, but are you open to any addition on the color scheme for twentysixteen? because I will try to work on some of it..

**Comment by SeanChDavis** [comment]
@junrillg I'm not the decision maker. I'm just here to provide feedback. I'm sure @karmatosed will come through to provide direction within the next day or so.

I would wait to see if he is open to adding more color schemes and then go from there. If so, I wouldn't mind seeing a blue template but something more in line with Twenty Fifteen or at least more blue.

**Comment by SeanChDavis** [comment]
I would actually suggest opening up an Issue (you should always do this) to start the discussion. https://github.com/WordPress/twentysixteen/issues/new Then you can link to the Issue from this PR using the Issue number like you see here: https ://github.com/WordPress/twentysixteen/pull/42 (broken link to prevent GitHub linking)

**Comment by karmatosed** [comment]
Adding new color schemes is heading into design territory, as a result we need @iamtakashi to have the deciding vote. It's important we maintain his vision.

**Comment by iamtakashi** [comment]
I don't think we need to add any more bundled colour scheme. The theme already bundles five colour schemes, and bundling colour scheme is never meant to satisfy everyone. That's why all of five colour slots are editable so that it's easy to modify and make your own colour scheme.

**Comment by iamtakashi** [comment]
Thank you for the PR but I'm closing this with the reason above.

**Comment by junrillg** [comment]
@iamtakashi no worries.

**Pull request closed without merging**
