### PR TITLE
Fix overflow blockquote in RTL

### PR DESCRIPTION
**Pull request by iamtakashi**
Also this changes the function name and the extra class name to be a little more descriptive. See #5

### CODE REVIEW

**Comment by tywayne** [comment]
Is there a reason why jscs was disabled here? It was correctly pointing out the misplaced variable declaration. All variables should be declared at the beginning of the function.

Disabling jscs to get around this occurs in other places as well, and it has never made sense to me why those instances of breaking [coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#declaring-variables-with-var) get a pass.

**Comment by iamtakashi** [comment]
I'm happy to change it. But could you let me know why we need to put it at the beginning of the function when we only need to create it with a certain condition?

**Comment by tywayne** [comment]
While in this specific instance it should not affect anything, it is best practice to declare all variables at the top of the function. This is typically requested because of potential inadvertent effects of var hoisting. A good explanation of var hoisting [can be read here](http://www.adequatelygood.com/JavaScript-Scoping-and-Hoisting.html).

If the concern is assigning `new Image()` only when needed, the var should be declared at the top, and assigned a value when the condition is met.

**Comment by iamtakashi** [comment]
Thanks for the clarification.

How about `entryContent` in the `belowEntryMetaClass()`? Does it also make sense to declare at the top and assign a value after the body class check?

**Comment by tywayne** [comment]
That one doesn't actually make sense to be a variable at all. Typically jQuery objects are stored in variables like that so they are cached to be re-used multiple times without having to perform the lookup again. The `entryContent` var is only used once in the whole function, and could easily just be replaced with it's value. 

So `entryContent.find()` could simply be `$( '.entry-content' ).find()`

But yes, if it does need to be stored in a variable, it would be best practice to declare the variable at the top and assign as needed.

**Comment by iamtakashi** [comment]
> That one doesn't actually make sense to be a variable at all

I was wondering about that.  It makes sense. I'll make a PR to fix these.

Thanks for pointing this out!

**Comment by iamtakashi** [comment]
Fixed above in #318

**Pull request merged**
