### PR TITLE
Modify some IF statements syntax to fit WordPress PHP Coding Standards

### PR DESCRIPTION
**Pull request by ihorvorotnov**
After studying the code I've spotted some incorrect usage of standard (curly braces) and alternative syntax for IF statements. As per WordPress PHP Coding Standards, alternative syntax should be used for complex chunks of code, mostly in templates where we mix PHP and HTML. For other cases, especially one-liners, curly braces should be used. 

Or, at the very least, we should have a system. If we obey to use alternative syntax when mixing PHP and HTML, let's do it everywhere (see changes in `template-parts/content-single.php` and `template-parts/content.php`). And for one-liners it's better to have braces (see changes in `inc/template-tags.php` for example).

Check WordPress PHP Coding Standards [here](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style).

### CODE REVIEW

**Comment by ihorvorotnov** [comment]
Sorry, messed up a bit with contributors and --amend. It's 7am here, my brain needs some sleep.

**Comment by grappler** [comment]
:+1:

**Comment by ihorvorotnov** [comment]
WTF! Looks like I messed up again :( Some old commits from deleted fork. Can anyone help me to fix this? Can't understand how it happened and how to remove these extra commits.

_I need a vacation..._

**Comment by karmatosed** [comment]
@ihorvorotnov not sure what you have done, I'd probably advise at this point to reset your fork.

**Comment by grappler** [comment]
@ihorvorotnov I am not sure this PR can be saved as the connection to the fork seems to be broken.

**Comment by ihorvorotnov** [comment]
I guess I'll make another clean PR for this issue and we'll just delete this one.

**Comment by karmatosed** [comment]
Closing as we need a clean version.

**Comment by karmatosed** [comment]
I'm not sure the standards prevent or suggest you shouldn't use endif. Can you point to where exactly that's outlined?

**Pull request closed without merging**
