### PR TITLE
fix #17 - hfeed class only on pages with multiple hentry elements

### LINKED ISSUE #17: HFeed should Only Appear on Archive Pages
See _s https://github.com/Automattic/_s/pull/743 

HFeed indicates a page where multiple hentrys exist. It should not appear on any single page.

### PR DESCRIPTION
**Pull request by karpstrucking**
I figured checking the post count would be simpler than checking a series of template tags. I'm assuming it's safe to use `$wp_query` here instead of `$wp_the_query`?

### CODE REVIEW

**Comment by karpstrucking** [comment]
Should I be using `is_singular()` here instead?

**Comment by dshanske** [comment]
That is what I use in my themes. Bear in mind that themes have been including it on all posts in error for some time.

**Comment by iamtakashi** [comment]
@karpstrucking, can you use `is_singular()` instead?

**Comment by karpstrucking** [comment]
@iamtakashi done

**Comment by karmatosed** [comment]
Can you refresh this please, to avoid conflicts.

**Comment by karpstrucking** [comment]
@karmatosed gladly. relatively new to using git collaboratively - what's the best method for this?

**Comment by karpstrucking** [comment]
@karmatosed I think I figure it out :)

**Comment by valendesigns** [comment]
@karpstrucking this should help get your master updated then you can merge from there http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository#answer-7244456

**Comment by karpstrucking** [comment]
@valendesigns thanks, that's actually the SO I ended up using a few days ago. When I did, the PR showed to be conflict free, so I'm not sure what's happened now. I just tried another rebase and don't see any conflicts now either.

**Comment by valendesigns** [comment]
You checked out your branch after the rebase and did `git merge --no-ff master`?

**Comment by karpstrucking** [comment]
@valendesigns I did now. I must have missed that in the article. Thanks!

**Comment by valendesigns** [comment]
Awesome thank you! It wasn't in that article, they're two different things.

**Comment by karpstrucking** [comment]
That sure makes my PR messy. Is there a way I can do this differently in future that doesn't include all the changes from the fast-forward?

**Comment by valendesigns** [comment]
It's only making the commit messy the actual PR is still clean. You can see above when you click on "Files changed" tab.

In regards to merging, a really good article I recommend you read if you haven't already is http://nvie.com/posts/a-successful-git-branching-model/

**Comment by karpstrucking** [comment]
ah, perfect - thanks again!

**Comment by karmatosed** [comment]
The PR is fine, the Travis checks aren't fully working yet (we're super close to them working).

**Comment by karmatosed** [comment]
Noting this is flagged for discussion in the next meeting: Friday 16:00 UTC in #core-themes.

**Pull request closed without merging**
