### PR TITLE
Make Twenty Sixteen compatible with WordPress.org translations.

### LINKED ISSUE #473: Remove .pot File from Theme
See: https://core.trac.wordpress.org/ticket/34884
- Theme translations started rolling out in 2015. See: https://make.wordpress.org/themes/2015/07/14/theme-translations-on-wordpress-org/
- Necessary changes were made to WordPress in https://core.trac.wordpress.org/changeset/22346 and https://meta.trac.wordpress.org/changeset/709
- Translations would now fully happen via https://translate.wordpress.org/ and `.pot` files and `languages` directory are no longer needed.

### PR DESCRIPTION
**Pull request by davidakennedy**
- Theme translations started rolling out in 2015. See: https://make.wordpress.org/themes/2015/07/14/theme-translations-on-wordpress-org/
- Necessary changes were made to WordPress in https://core.trac.wordpress.org/changeset/22346 and https://meta.trac.wordpress.org/changeset/709
- Translations would now happen via https://translate.wordpress.org/ and `.pot` files are no longer needed.

Fixes #473

### CODE REVIEW

**Comment by grappler** [comment]
I would make the URL directly to the project 

> Translate to your language on WordPress.org. See: https://translate.wordpress.org/projects/wp-themes/twentysixteen

**Comment by davidakennedy** [comment]
Good suggestion, @grappler! I updated the PR. I feel silly because I actually looked for a more specific URL but only found the locale specific ones.

**Comment by grappler** [comment]
👍 I feel the sentence "Translations can be filed at WordPress.org." is a bit strange as a translator does not fill the translation but translates the strings.

**Comment by davidakennedy** [comment]
Yeah, I kept the verb the same as it was previously. In some older default themes, `add` is used. Add is probably a better, more natural verb to translate, right?

**Comment by grappler** [comment]
My suggestion would be "Translate into your language on WordPress.org.". Add and fill sort of expect the translation to be ready and just needing to copy and pasted whereas the translation work is done on w.org.

**Pull request merged**
