### PR TITLE
Add since parameter in twentysixteen_custom_header_and_background - fix #11

### LINKED ISSUE #11: `since` parameter missing in doc of `twentysixteen_custom_header_and_background` function
File: `custom-header.php`
Function: `twentysixteen_custom_header_and_background`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by shivapoudel** [comment]
@wenthemes leave the indentation as it is.

**Comment by karmatosed** [comment]
@wenthemes can you make a version without the indenting changes please?

**Comment by karmatosed** [comment]
This is now out of sync, can you refresh and resend in please?

**Comment by iamtakashi** [comment]
No need to refresh. It's already fixed in https://github.com/WordPress/twentysixteen/commit/7df4ba37ef0457066d5f1223d75a043d01be3be8

**Comment by karmatosed** [comment]
Ah, thanks.

**Pull request closed without merging**
