### PR TITLE
Fix some Javascript Coding Standards issues reported by Trevis CI

### PR DESCRIPTION
**Pull request by ihorvorotnov**
This PR fixes all minor (formatting) issues in current js codebase. However, there are some issues that need discussion. See #143 for details.

### CODE REVIEW

**Comment by philiparthurmoore** [comment]
These look good. Can you squash the commits via rebase? 1 commit for these changes would look much better in history.

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by ihorvorotnov** [comment]
@philiparthurmoore I agree. We agreed with @iamtakashi for a commit per modified file, but after code review it can be safely squashed.

Update: Done.

**Comment by iamtakashi** [comment]
I've suggested a PR for each file because I thought all issues were going to be fixed at the same time and wanted to test file by file.

But in this case, yes. this is better. Thank you!

**Comment by philiparthurmoore** [comment]
That was fast! Thanks @ihorvorotnov and @iamtakashi.

**Comment by ihorvorotnov** [comment]
@philiparthurmoore thank you for help :+1:

**Pull request merged**
