### PR TITLE
Remove unneeded spaces

### PR DESCRIPTION
**Pull request by grappler**

### CODE REVIEW

**Comment by iamtakashi** [comment]
Do we really have to remove the space? I think it's ok to call it on separate line. Twenty Fifteen also does this.

**Comment by MonikaTS** [comment]
a) lines are better readable for humans
b) without white space it is faster for machines //bots //browser 
is it necessary that humans read inline css? 

if not than one line is better for performance...

**Comment by fklein-lu** [comment]
Removing the space makes the line too long IMO, and when chaining functions it's definitely more readable to have the line break.

Talking about performance is pointless, since with or without space makes no difference whatsoever.

**Comment by grappler** [comment]
If it is too long then single people can change the setting in their IDE to wrap the text. I find it easier to read when it is all on one line.

**Comment by fklein-lu** [comment]
Automatic text wrapping is not a replacement for intended line breaks.

**Comment by iamtakashi** [comment]
I don't think this is necessary. I'm closing this for now.

**Comment by grappler** [comment]
Ok, can you reopen the PR so that I can change it to comply to the coding standard "[chained method calls](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#chained-method-calls)"

The problem is also that spaces have been used instead of tabs.

**Comment by iamtakashi** [comment]
Please Make a new one with a little more descriptive title and description.

**Pull request closed without merging**
