### PR TITLE
Update archive.php

### PR DESCRIPTION
**Pull request by 8bittts**
small comment change. see context here: https://github.com/WordPress/twentysixteen/pull/163

### CODE REVIEW

**Comment by ihorvorotnov** [comment]
You shouldn't add a space at the beginning of the file. According to WP Coding Standards (and, afaik, PSR) there should be no blank lines after `<?php` opening tag.

And there's something wrong - Travis CI isn't running a build job properly. @philiparthurmoore can you check it when you have a minute?

**Comment by philiparthurmoore** [comment]
```
Cloning into '/tmp/wordpress'...
fatal: unable to connect to develop.git.wordpress.org:
develop.git.wordpress.org[0: 66.155.40.244]: errno=Connection timed out
```

Builds can always be re-run manually. Either way this isn't a good Pull Request and IMO should be closed.

**Comment by ihorvorotnov** [comment]
@philiparthurmoore yep, I know. However, we added Travis CI as **automatic** check in the first place. Is there anything we can do to prevent this kind of errors? (Though I understand it's on .org side).

Regarding PR itself - @saddington submitted several PRs, some of them (like this one) are not valid, however, some are worth checking. I proposed to combine them into one PR and re-submit so we can check it line by line.

**Comment by philiparthurmoore** [comment]
> However, we added Travis CI as **automatic** check in the first place. 

Not much you can do when the server from .org's side isn't responding. That has nothing to do with Travis. I get connect errors in my localhost debug.log all the time. It's part of working with other servers.

Easy enough to run a PR through a check again if it's considered a pull request worth merging:
http://stackoverflow.com/a/17624403

**Comment by ihorvorotnov** [comment]
@philiparthurmoore thanks for clarification

**Comment by karmatosed** [comment]
I agree with @philiparthurmoore about this PR, so for now lets close.

**Pull request closed without merging**
