### PR TITLE
Remove `$more` parameter as not used; minor code formatting

### PR DESCRIPTION
**Pull request by Cais**
Replacement for PR#110

### CODE REVIEW

**Comment by karmatosed** [comment]
This unfortunately seems out of sync, can you please update?

**Comment by Cais** [comment]
This was in sync when I creating the PR (same as the first time) ... the premise is quite easy, although not strictly necessary, just cleaner code IMHO so if something else comes up I'll refresh this again but otherwise I'm fine with it being closed as is.

**Comment by karmatosed** [comment]
I'll take a go at this tomorrow for you to hopefully avoid the refreshing issue.

**Comment by Cais** [comment]
The `$more` parameter is fine to include but it's not actually needed or used in the method ... my guess is the branch conflicts are more likely in the code formatting that is also applied to the file in general (which I do out of habit before I look at anything else).

Just have a look at this line in particular: https://github.com/WordPress/twentysixteen/blob/master/inc/template-tags.php#L181 (at least as of this writing).

**Comment by karmatosed** [comment]
I've removed the $more. This was in other default themes, so we could do with investigation, but it does make sense to remove.

**Pull request closed without merging**
