### PR TITLE
add function description

### PR DESCRIPTION
**Pull request by mt8**

### CODE REVIEW

**Comment by grappler** [comment]
:+1:

**Comment by ihorvorotnov** [comment]
That case when commit messages in PR speak better than any PR description would.

**Comment by iamtakashi** [comment]
@mt8, what's your WordPress.org username? I'll add your username to the contributors list.

**Comment by mt8** [comment]
Hi, my WordPress.org username is mt8.biz

**Comment by karmatosed** [comment]
Could we get a refreshed patch for this please @mt8 ?

**Comment by mt8** [comment]
Here is new patch. @karmatosed

**Comment by karmatosed** [comment]
Thanks, going to merge this.

**Pull request merged**
