### PR TITLE
replace single.php and page.php with singular.php

### PR DESCRIPTION
**Pull request by mathetos**
REFRESHED PR for https://github.com/WordPress/twentysixteen/pull/144

This PR makes single.php and page.php unnecessary because of the conditionals in singular.php, the relatively new WordPress template page. This makes the theme lighter code-wise, and uses less actual files while highlighting the possibilities of the new template file.
- post navigation is added to attachment pages

### CODE REVIEW

**Comment by valendesigns** [comment]
You need to update this PR to use tabs not spaces.

**Comment by mathetos** [comment]
I was told the opposite previously.

**Comment by valendesigns** [comment]
WordPress coding standards are to use tabs not spaces. https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation

**Comment by mathetos** [comment]
Maybe I misunderstood before. That makes it very clear. Will refresh the PR.

**Comment by ihorvorotnov** [comment]
@mathetos also please check Travis CI logs. Ignore everything js-related - I'm taking care of it right, but please see if there's also anything related to your code.

**Comment by mathetos** [comment]
Refreshed PR submitted here: https://github.com/WordPress/twentysixteen/pull/165 

As requested indents are all tabs now. Also checked the Tavis CI logs and fixed any errors that resulted from this new file.

**Pull request closed without merging**
