### PR TITLE
_e converted to esc_html_e

### PR DESCRIPTION
**Pull request by maharzan**
For more security. Issue: https://github.com/WordPress/twentysixteen/issues/118

### CODE REVIEW

**Comment by karmatosed** [comment]
Can you update this to make it be in sync please?

**Comment by maharzan** [comment]
I m new to this, not sure if that went well.. Let me know if I need to do something else. Thanks.

**Comment by karmatosed** [comment]
@maharzan no problem, can you make sure you update your fork before doing a PR? It still seems out of sync.

**Comment by maharzan** [comment]
I did pull it before doing the PR and it said uptodate, just like now. :) I hope this one is okay.

**Pull request merged**
