### PR TITLE
Small comment change

### PR DESCRIPTION
**Pull request by 8bittts**
One block of text had a different comment treatment. Just changed it for more consistency.

### CODE REVIEW

**Comment by ihorvorotnov** [comment]
This one looks good for me. I would change asterisks used for unordered list to hyphens though.

However, all these changes should go in one PR.

**Comment by grappler** [comment]
The script has just been copied from https://github.com/afarkas/html5shiv It is better to make the PR there.

**Comment by ihorvorotnov** [comment]
@grappler good point :+1:

**Comment by philiparthurmoore** [comment]
I don't see any significant benefit of merging a PR like this. Pretty much +1 to what @grappler wrote as well.

**Comment by karmatosed** [comment]
For now let's close this.

**Pull request closed without merging**
