### PR TITLE
update post navigation placeholder(s) for consistency

### PR DESCRIPTION
**Pull request by karpstrucking**
addresses issue #114

### CODE REVIEW

**Comment by iamtakashi** [comment]
It'd be better to not introduce a new color, `#6a6a6a` to make it work well with the color scheme option. Instead, let's keep it white and adjust the color with opacity.

Also there are a bunch of selectors that use Genericons at section 2.0 in the stylesheet. The two selectors should be added there.

Lastly, the color of arrows should match with each the page background color option in each color scheme. You will need to add the selectors appropriate places in `twentysixteen_get_color_scheme_css()` and `twentysixteen_page_background_color_css()`.

**Comment by karpstrucking** [comment]
@iamtakashi good feedback, thank you - will update the PR accordingly

**Comment by karpstrucking** [comment]
@iamtakashi PR updated. I'm going to need some guidance on getting the color to update live in the Customizer, though - new ground for me.

**Comment by iamtakashi** [comment]
@karpstrucking, 

No worries! I actually didn't realise an issue with the approach I suggested but here is what I've done —#142. I needed a bit of CSS than I thought, my idea was to not to make the custom colour side of code complicated in `customizer.php`. Hope it helps. And thanks for working on this!

**Pull request closed without merging**
