### PR TITLE
Increase site-description line-height

### PR DESCRIPTION
**Pull request by emiluzelac**
To fix this small cut-off at the bottom of description, I would recommend increasing the line-height. Here's how this looks like: http://envato.d.pr/171h0/5HHngCXz

Please don't pay attention to what description says, this was for an internal project, not meant to be for this :)

### CODE REVIEW

**Comment by iamtakashi** [comment]
Thanks for the report Emil.

I hesitate to change the line height to keep the vertical rhythm with a baseline grid.

This looks like a side effect of #441, specifically `overflow: hidden`. Good thing is that since then max size of custom logo has been changed so #440 might not be a legit issue and we could remove #441 so that the cut-off doesn't happen.

We'll test it further.

**Comment by emiluzelac** [comment]
My pleasure @iamtakashi. Should I close it?

**Comment by iamtakashi** [comment]
The cut-off issue is legit and we should fix it for the next version anyway, so could you open a new issue and close this PR?

**Comment by emiluzelac** [comment]
Cool, so create a PR to reverse? https://github.com/WordPress/twentysixteen/pull/441

**Comment by iamtakashi** [comment]
No, I think it's usually better to make an issue first and then link a PR to fix the issue if you like.

**Comment by iamtakashi** [comment]
A new issue made #454.

**Comment by emiluzelac** [comment]
Cool sorry, I just came back home 👍🏻

**Pull request closed without merging**
