### PR TITLE
No need to translate URL and simplified writing anchor text to screen

### PR DESCRIPTION
**Pull request by Cais**

### CODE REVIEW

**Comment by grappler** [comment]
It makes sense to translate the URL as there are urls for different languages e.g. de.wordpress.org for the German community

**Comment by Cais** [comment]
Although I do understand your point, the context of the anchor text itself does not lend itself to the URL being for a specific community versus the WordPress project as a whole.

**Comment by karmatosed** [comment]
I'm kind of torn. I do see both sides to this. Lets discuss in the weekly meeting on Monday.

**Comment by ihorvorotnov** [comment]
I agree with @grappler. 

That's another case of "**there's life outside US**" issue. There are different countries and WordPress.org has localized sites.

> URL being for a specific community versus the WordPress project as a whole

it's not **community**, not more then WordPress.org itself, because it actually is just a translated website, including documentation and support forums. Please, understand, there are people in other countries all over the world who **don't** speak english at all. I mean, zero. They use localized versions of WordPress.org, they use localized versions of WordPress software. So it 100% makes sense to have that lang.wordpress.org link instead of just main website. Unless WordPress.org detects one's location  and preferences and loads proper localized version automatically, allowing to override it via cookie and settings though (if I speak english and prefer EN version over my local).

**Comment by philiparthurmoore** [comment]
^ This.

Vietnamese people in general rely 100% on the Vietnamese translations and localized site that we make. English isn't spoken a lot here. They belong to their own WordPress community and we should make that easier for them to find via any means possible.

**Comment by karmatosed** [comment]
As there has been a lot of vocalisation around this, lets close for now.

**Comment by Cais** [comment]
Fair enough ... perhaps this is an issue larger than the theme itself.

**Pull request closed without merging**
