### PR TITLE
Remove unnecessary calls to escaping functions

### LINKED ISSUE #190: Escaping review
There is a fair bit of to and fro about escaping and when too much is going on (or not enough). As we talked about in this weekly meeting, lets now bring that here to give everyone a chance to suggest a way through this. In the past, when a default theme goes into core it has had a ticket removing a lot of work done because of over escaping. Lets try and minimise that this time and find a way to make this work from now on.

Pinging a few people to get the conversation rolling: @fklein-lu @dd32 @ocean90

### PR DESCRIPTION
**Pull request by ocean90**
Fixes #190

### CODE REVIEW

**Comment by karmatosed** [comment]
On trying to merge this I'm seeing conflicts. Could you try refreshing the PR please?

**Comment by ocean90** [comment]
@karmatosed Refreshed.

**Comment by karmatosed** [comment]
Thanks, all tested and going to merge.

**Comment by philiparthurmoore** [comment]
Is there a discussion link that references why all the escaping was taken out? Thanks.

**Pull request merged**
