### PR TITLE
Remove unwanted php closing tag

### PR DESCRIPTION
**Pull request by vishalkakadiya**

### CODE REVIEW

**Comment by vishalkakadiya** [comment]
Please note that travis built is failed because of phpcs issues in functions.php file.

**Comment by ntwb** [comment]
Previously #497

**Comment by ntwb** [comment]
Note: Please do not merge this PR until a decision/consensus has been agreed upon for what themes to make these changes to as part of https://core.trac.wordpress.org/ticket/40039

**Comment by davidakennedy** [comment]
Since Twenty Sixteen is no longer maintained on GitHub (see: https://core.trac.wordpress.org/ticket/36497), let's move all conversation to https://core.trac.wordpress.org/ticket/40039

@vishalkakadiya Please refresh your patch there. Sorry for the inconvenience! 😮

**Pull request closed without merging**
