### PR TITLE
apply hyphens CSS to content titles #34

### PR DESCRIPTION
**Pull request by SeanChDavis**
#34

### CODE REVIEW

**Comment by SeanChDavis** [comment]
@iamtakashi All the research I've done uses `word-break` as a proper fallback for `hyphens`. From what I understand, it breaks in a slightly different manner than `word-wrap: break-word;` and is more consistent with what `hyphens` is tasked to do. You can read about it here: https://kenneth.io/blog/2012/03/04/word-wrapping-hypernation-using-css/ Let me know what you think.

**Comment by iamtakashi** [comment]
Lots of themes in WordPress.com used to have this rules but we've stopped it completely after hearing lots of complains about unreadable text because it completely destroys word level breaking in IE9, Firefox and possibly more browsers.

I also remember this ticket. https://core.trac.wordpress.org/ticket/21503

We're not able to release updates for default themes as often as any other themes, we should stick with what's proved to be the safest option in the past default themes, therefore I'd say let's stick to use only `word-wrap: break-word;` and add hyphens to the titles to see if it works well.

**Comment by SeanChDavis** [comment]
@iamtakashi Totally understand. PR refreshed. Let me know if you agree with that implementation.

**Comment by iamtakashi** [comment]
Thanks for the update. I should've spotted before but let's add `-ms-hyphens: auto;` for IE users so that they can have the benefit of hyphens.

**Comment by SeanChDavis** [comment]
@iamtakashi No worries! PR refreshed.

**Pull request merged**
