### PR TITLE
Add support for theme template hooks

### PR DESCRIPTION
**Pull request by chipbennett**
Relies heavily on the work of @zamoose and the @zamoose/themehooksalliance, with a few changes.

This is a first-pass effort. I'm open to all feedback regarding adding/removing/or changing the locations of the template hooks, as well as the naming convention.

The naming convention used is: `template_[section]_[placement]`, where `[section]` includes e.g. `header`, `footer`, `content`, `entry`, `sidebar`, etc., and where `[placement]` is generally `before`, `top`, `bottom`, or `after`.

### CODE REVIEW

**Comment by philiparthurmoore** [comment]
Unrelated to actual issue raised: lots of newline problems with this PR: https://travis-ci.org/WordPress/twentysixteen/jobs/79888834.

**Comment by ihorvorotnov** [comment]
@chipbennett .editorconfig helps a lot. You might be aware of it, I'm sure :wink:

**Comment by karmatosed** [comment]
Lets have this as a discussion in our weekly meeeting. I think it's a good idea to give it a good airing. Personally, I am not that keen we put this in. It's not something everyone is using currently or I personally see a need even in wider use for currently beyond personal preference. I'm not sure it's right this year in the default theme. However, that is purely my own opinion. I'm keen to let as many as possible get their opinion in here.

**Comment by ianstewart** [comment]
@chipbennett I wonder if this should be a core ticket first, outside of a particular default theme. Like, "Support the hooks proposed by the Theme Hook Alliance in default themes." Where discussion on the idea would happen in general. It seems like a big decision to add non-prefixed hooks to default theme winging it's way to inclusion in a scheduled release.

**Comment by chipbennett** [comment]
We have a cart-horse issue. We need to go one route or the other.

IIRC, the last status of the core ticket was, "it's premature in core;
let's get it in a core theme first, and go from there". Now, I've patched
it in a core Theme, and the first response is: let's put it in core first.

I honestly don't care which route we take. But I think it's  time to decide.

As for firing the hooks themselves: they absolutely should be in the core
Theme(s). It really should just be a matter of deciding what template
locations should have associated hooks.

**Comment by chipbennett** [comment]
Related (old, as usual) core ticket:

https://core.trac.wordpress.org/ticket/21506

**Comment by karmatosed** [comment]
I have thought a bit about this and really do think it's something to approach this time in core. We can chat on Friday again. But, I really think it's worth that route as the first option.

**Comment by chipbennett** [comment]
So, I will be more than happy to create a core patch for the hook template
tag functions. Can I ask that we keep this PR open until we get some buy-in
on the existing core ticket, from @wonderboymusic? If we have a blessed
path forward, I'll be happy to run with it.

**Comment by karmatosed** [comment]
As we are merging this into core in a few weeks, I'm not sure what having this open does to support that. You can still link even if it's closed. We're simply saying that the default theme isn't right place for it right now. 

I can't say if this will get into core either, that's up for a conversation there.

**Comment by chipbennett** [comment]
Fair enough. I'll link the closed PR back in the core trac ticket, and
point out how the issue is getting dragged in circles. Maybe the core dev
team will get the point, and make a decision.

**Comment by karmatosed** [comment]
Thanks, closing as discussed.

**Pull request closed without merging**
